### ISSUE TITLE
Can this be used for specific mods?

### ISSUE THREAD

**Issue by randycarrero** [robojumper/steam_workshop_discord#1]
can i place the ids of the workshop instead of the game ids. 
Would be great if we can have it that way. would be like the only one that's able to do it.

**Comment by robojumper** [comment]
Sorry I missed this, guess I wasn't getting notifications for this repo.

I actually have no idea what you're asking though. I'm using this for XCOM 2 to send messages for every newly released XCOM 2 mod. The XCOM 2 game ID is 268500, and the workshop link is <https://steamcommunity.com/app/268500/workshop/>. Can you describe your use case in a bit more detail?

**Comment by randycarrero** [comment]
https://steamcommunity.com/sharedfiles/filedetails/changelog/2201956436

sorry for the delay

**Comment by robojumper** [comment]
Changelogs are currently not supported at all. There are two reasons:

1. The Steam Web API does not expose the changelog, so one would have to request and parse the HTML web pages
2. Requesting changelogs for every single mod requires way too many requests

I'm personally not inclined to support this until the Steam API provides the changelog directly.

**Comment by randycarrero** [comment]
I see thank you im a novice to all this.
